### PR TITLE
Mariam

### PR DESCRIPTION
**Pull request by mariamgrig**
I did a bunch of show/view aesthetic changes plus added a new customs css. Added a couple partials for a new header and a footer in the layouts. Also added a static about page. The show view is represented as a pop-up container now. Still need to work on a couple minor changes/css clean up and form design.

### CODE REVIEW

**Comment by amycsong98** [comment]
can you pull this branch and delete all the tmp/cache files?

**Comment by Allegraknox** [comment]
Looks good! Remove the binary files though, those are just junk

**Comment by amycsong98** [comment]
undo the commit.
git checkout tmp/cache/*
commit again
push.

**Comment by mrubakh** [comment]
> undo the commit.
> git checkout tmp/cache/*
> commit again
> push.

We also need to get rid of the log/* and db/* --> it might be easier just to manually add every file you worked on or do a set of shortcuts such as 

`git add app/* coverage/* config/* spec/*` for the directories that do provide meaningful changes

**Pull request closed without merging**
