### PR TITLE
added simple JSON test for autocomplete

### PR DESCRIPTION
**Pull request by mrubakh**
coverage --> 100%

### CODE REVIEW

**Review by amycsong98 — APPROVED** [review]
cool!

**Comment by amycsong98** [comment]
while you're at it, can you please move the search bar back to the top of the list?

**Comment by mrubakh** [comment]
> while you're at it, can you please move the search bar back to the top of the list?

done!

**Comment by mrubakh** [comment]
> while you're at it, can you please move the search bar back to the top of the list?

sure!

**Pull request merged**
