### PR TITLE
refactor delete to unlist

### PR DESCRIPTION
**Pull request by meg-imperato**
now users can mark items as unlisted and they no longer show in index view (but still remain in the database)
still need to implement to cucumber step to accept the popup, other than that, tests should be done

### CODE REVIEW

**Comment by amycsong98** [comment]
i wonder if this makes `destroy` rspec test fail--did you run `rails spec` to double check?

**Comment by meg-imperato** [comment]
> i wonder if this makes `destroy` rspec test fail--did you run `rails spec` to double check? / edit the `destroy` rspec test?

You're right, I just fixed them!

**Review by amycsong98 — APPROVED** [review]
LGTM but question: should the two test files be renamed from destroy to unlist? (i don't have a preference, but just a thought)

**Comment by meg-imperato** [comment]
> LGTM but question: should the two test files be renamed from destroy to unlist? (i don't have a preference, but just a thought)

I renamed them (I think it should show by the top of each file). That way we can add destroy as a separate thing if we decide we want it later for some other reason.

**Pull request merged**
